"""empty message

Revision ID: 617e578e3398
Revises: 6cac27e40714
Create Date: 2025-04-16 15:37:07.648082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617e578e3398'
down_revision = '6cac27e40714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.drop_constraint('bookmarks_card_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.create_foreign_key('bookmarks_card_id_fkey', 'cards', ['card_id'], ['id'])

    # ### end Alembic commands ###
