"""empty message

Revision ID: 6df59b3a15e7
Revises: fbd73fcf88b1
Create Date: 2025-01-26 12:19:47.567260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df59b3a15e7'
down_revision = 'fbd73fcf88b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('question_answer')
        batch_op.drop_column('student_answer')
        batch_op.drop_column('result')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('student_answer', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('question_answer', sa.VARCHAR(length=80), nullable=False))

    # ### end Alembic commands ###
