"""empty message

Revision ID: 78f1e38d162f
Revises: 64c744499b9f
Create Date: 2025-04-08 13:22:11.650936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78f1e38d162f'
down_revision = '64c744499b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isCorrect', sa.String(), nullable=True),
    sa.Column('diff', sa.Integer(), nullable=True),
    sa.Column('json_column', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('card')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('json_column', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('isCorrect', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('diff', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='card_pkey')
    )
    op.drop_table('bookmarks')
    op.drop_table('cards')
    # ### end Alembic commands ###
