"""empty message

Revision ID: 8be32d7f0894
Revises: 78f1e38d162f
Create Date: 2025-04-11 08:48:28.280400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8be32d7f0894'
down_revision = '78f1e38d162f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('card', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('card')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
