"""empty message

Revision ID: 93e8727fb44f
Revises: 04ddd760cd93
Create Date: 2025-04-18 16:21:24.227071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e8727fb44f'
down_revision = '04ddd760cd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.alter_column('card_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isBooked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_column('isBooked')

    with op.batch_alter_table('bookmarks', schema=None) as batch_op:
        batch_op.alter_column('card_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
